### ISSUE TITLE
Empty HTTP response leading to error "'NoneType' object has no attribute 'split'" when reusing an existing device

### ISSUE THREAD

**Issue by francescoraimondi** [synacktiv/SCCMSecrets#3] opened 2024-09-18 11:58 UTC
Hi!

First of all, thanks for the great tool! :) 

To be clear, this is not a duplicate of [https://github.com/synacktiv/SCCMSecrets/issues/1](url), altho it leads to a similar exception. I looked at the linked issue and tried to replicate the same scenario (reusing an existing device providing the guid and the private key and making sure I had the client name passed as parameter as well), but I get the exception "'NoneType' object has no attribute 'split'".

I investigated a bit with wireshark and it seems that after the CCM_POST request, the Management Point replies with a 200 OK but no body (where the script is expecting to receive the multipart document with the policies). 

One thing I should add, is that this is not a device that has been previously registered through SCCMSecrets - it is a machine that was already registered as an asset, but has been compromised and the certificate private key has then been exported. 

I'll try to add some picture, but it will take a while as I have to redact quite a bit of info.

**Comment by q-roland** [comment] 2024-09-22 17:58
Hi,

Thanks for reporting the issue. I was not able to reproduce it in my testing environment, where providing the extracted GUID and private key of a legitimate SCCM client allows the script to retrieve the list of policies (and thus execute the next steps without issues).

I observed the behaviour you are describing (management point returning an empty 200 OK response instead of the policies list) when either the PEM private key or the GUID does not match the one of the registered device. A few questions for you to help pinpoint the issue:

- Are you sure that the GUID is the one of the legitimate device (did you verify it for instance from the `C:/Windows/CCM/Logs/ClientIDManagerStartup.log` file, or directly in the SCCM console if you have admin access) ?
- Are you sure that the PEM private key is indeed the one related to the certificate of the device (how did you extract it / was it indeed associated with the cert called `SMS Encryption Certificate` in the Windows store of the client device) ?

Out of curiosity, what is the version of the SCCM installation on which you are working ?

Cheers :)

**Comment by francescoraimondi** [comment] 2024-09-23 07:17
Thanks a lot for the quick reply and assistence!

I think this issue can be closed. Using the tips you provided, I double checked the certificate extracted (using SharpDPAPI certificates /machine) and I realized it's not the correct one. I wrongly assumed it was, since it's the only one that SharpDPAPI is able to export from the Local Machine store... not sure what the problem is there and why it can't extract anything else, but it definitely isn't SharpSCCM :) 

Thanks a lot for pointing me out in the right direction!

EDIT: Just for curiosity and added info, I just figured out that the reason why SharpDPAPI can't extract that certificates private key is because it is stored in the TPM :)

**Comment by q-roland** [comment] 2024-09-23 20:53
I'm glad you were able to solve your issue. Your point about private key that can sometimes be stored in the TPM is also interesting. I didn't know this was possible, but it could constitute a good mitigation against client device impersonation.

I'm closing this issue, thanks again for the info :)

**Closed as completed by q-roland** 2024-09-23 20:53 UTC
